### ISSUE TITLE
Start multiple server

### ISSUE THREAD

**Issue by Mrinal-Bhattacharya** [WASdev/ci.gradle#56] opened 2017-04-12 09:37 UTC
How can we start/stop multiple server in different port.

**Comment by cthigh** [comment] 2017-07-31 21:45
The current plugin just allows the creation of a single names server. It sounds like you are interested in creating multiple servers under the same runtime, with different server config (ports). 

Can you give a little more information on your use case?  Would you be installing the same application(s) to each server and just setting different configuration?

**Comment by Mrinal-Bhattacharya** [comment] 2017-08-02 12:29
Yes you are right we have a test case to test cache in clusters environment. So we required two server with different configurations. If this feature get added then it will help to many other users. You can check on issues section like many people asking for this feature.

**Comment by chyt** [comment] 2018-02-05 16:40
This is currently in progress. Closing as this is a duplicate of #45.

**Closed by chyt** 2018-02-05 16:40 UTC
